# Generated by Django 2.0 on 2019-11-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191127_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='about',
            field=models.TextField(default="Information about the company is not available."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblisting',
            name='vacancy',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]

